remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: STORM Coalition
description: Since 1989 the Save The Oak Ridges Moraine Coalition has focused on protecting the ecological integrity of the Oak Ridges Moraine through grassroot efforts.
logo: /assets/img/logo.png
