remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: Save The Oak Ridges Moraine Coalition
description: Since 1989 the STORM Coalition has focused on protecting the ecological integrity of the Oak Ridges Moraine through grassroot efforts.
